version: '3'
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    # enviroment variable to get auth api service name.
    # So that we can use it for both docker-compose and kubernetes
    environment:
      AUTH_ADDRESS: auth
    ports:
      - '8080:8080'
  tasks:
    build: ./tasks-api
    ports:
      - '8000:8000'
    environment:
      TASKS_FOLDER: tasks
