apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: sameer59/kub-data-demo:1
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # the volume type for this pod is below claim.
          # So we will use the volume created or accessed by below claim as a volume for this pod now.
          # You can use one of the same claim in different types of pods.
          # Now, this volume not created specifically for this pod, but instead for the entire cluster.
          persistentVolumeClaim:
            claimName: host-pvc
