apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment

# configuring deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  # pod details
  template:
    metadata:
      labels:
        app: tasks
    # configuration for this pod
    spec:
      containers:
        # container 1
        - name: tasks
          # when using the latest tag, by default kubernetes always refetches and re-evaluates the image
          # when something changes about our deployment configuration.
          image: academind/kub-demo-tasks:latest

          env:
            - name: TASKS_FOLDER
              value: tasks

            # need to set this env variable so that tasks api can talk to auth api
            - name: AUTH_ADDRESS
              # Way 1: Using cluster IP address of auth service. (Annoying approach)
              #value: 'xx.xx.xx.xx'

              # Way 3 - using cluster internal domain names.
              # This CoreDNS service which is installed in your cluster, automatically creates domain names
              # which are available and known inside of the cluster for all your service objects.
              # The generated domains names are same as service names, followed by a dot and namespace.
              value: 'auth-service.default'
