apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  # select pods
  selector:
    app: tasks
  # for outside access
  type: LoadBalancer
  # expose ports as defined in tasks-api/Dockerfile
  ports:
    - protocol: TCP
      # outside port
      port: 8000
      targetPort: 8000
