apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment

# configuring deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  # pod details
  template:
    metadata:
      labels:
        app: users
    # configuration for this pod
    spec:
      containers:
        # container 1
        - name: users
          # when using the latest tag, by default kubernetes always refetches and re-evaluates the image
          # when something changes about our deployment configuration.
          image: academind/kub-demo-users:latest
          # need to set this env variable so that users api can talk to auth api which is part of same pod.
          env:
            - name: AUTH_ADDRESS
              # Way 1: Using cluster IP address of auth service. (Annoying approach)
              value: 'xx.xx.xx.xx'
